data:
    container_name: lumen_data
    image: busybox
    volumes:
        - ../:/var/www/lumen
        - /vendor
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
        - ~/.composer:/root/.composer
        - /tmpfs

nginx:
    container_name: lumen_nginx
    image: nginx:1.7
    links:
        - php
    volumes_from:
        - data
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

mysql:
    container_name: lumen_mysql
    image: mysql:5.5
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: appdevdb

php:
    container_name: lumen_php
    build: php
    working_dir: /var/www/lumen
    volumes_from:
        - data
    links:
        - mysql
    mem_limit: 2000000000
